nelmio_api_doc:
    resource: '@NelmioApiDocBundle/config/routing/swaggerui.xml'
    prefix: /api/doc

# Add JSON endpoint for API documentation
api_doc_json:
    path: /api/doc.json
    methods: [GET]
    controller: nelmio_api_doc.controller.swagger_json
